version: '3.4'
# This is for local development

volumes:
  streaming:
  storage:
  database:
  fedora:
  solr:
networks:
  avalon-network:
    #network_mode: host

services:
  db:
    image: postgres:10-alpine
    volumes:
      - database:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=avalon
      - POSTGRES_DB=avalon
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      avalon-network:

  fedora:
    image: avalonmediasystem/fedora:4.7.5
    build: ./fedora
    depends_on:
      - db
    volumes:
      - fedora:/data
    environment:
      - JAVA_OPTIONS=-Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.home=/data
    networks:
      avalon-network:

  solr:
    image: avalonmediasystem/solr:latest
    build:
      context: ./solr
      args:
        - AVALON_BRANCH=v7.2.1
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    networks:
      avalon-network:

  hls:
    image: avalonmediasystem/nginx:latest
    build:
      context: ./nginx
    environment:
      AVALON_DOMAIN: http://uva-avalon:3000
    volumes:
      - streaming:/data
      - ./nginx/logs:/var/log/nginx:rw
    ports:
       - "8880:80"
    networks:
      avalon-network:

  redis:
    image: redis:alpine
    networks:
      avalon-network:

  uva-avalon: &avalon
    image: avalonmediasystem/avalon:7.2.1
    #platform: linux/arm64 # May be needed for arm Macs
    build:
      context: ./
      target: dev
    command: bash -c "bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0"
    depends_on:
      - db
      - fedora
      - solr
      - redis
      - hls
    environment:
      - APP_NAME="UVA Library Avalon"
      - SECRET_KEY_BASE=abc
      #- ASSET_HOST=localhost
      - SETTINGS__DOMAIN=http://localhost:3000
      - DATABASE_URL=postgres://avalon:@db/avalon
      - SETTINGS__ENCODING__WORKING_FILE_PATH=/masterfiles
      - SETTINGS__ACTIVE_STORAGE__SERVICE=local
      - SETTINGS__TIMELINER__TIMELINER_URL=http://localhost:3000/timeliner
      - SETTINGS__EMAIL__COMMENTS
      - SETTINGS__EMAIL__NOTIFICATION
      - SETTINGS__EMAIL__SUPPORT
      - ENCODE_WORK_DIR=/streamfiles
      - FEDORA_BASE_PATH
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - SETTINGS__MASTER_FILE_MANAGEMENT__STRATEGY=move
      - SETTINGS__MASTER_FILE_MANAGEMENT__PATH=/masterfiles
      - SETTINGS__DROPBOX__PATH=/masterfiles/dropbox
      - SETTINGS__DROPBOX__UPLOAD_URI=/masterfiles/dropbox
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=http://solr:8983/solr/avalon
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__STREAMING__HTTP_BASE=http://localhost:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
    volumes:
      - ./masterfiles:/masterfiles/:rw
      - storage:/home/app/avalon/storage/:rw #Config another location in storage.yml
      - streaming:/streamfiles/:rw
    ports:
      - "3000:3000"
    networks:
      avalon-network:
  worker:
    <<: *avalon
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []
    networks:
      avalon-network:

