units:
  - OLE
  - Albert and Shirley Small Special Collections Library
  - Robertson Media Center
  - University of Virginia School of Architecture
  - University of Virginia McIntire Department of Music
  - Women, Gender, and Sexuality Program
  - University of Virginia Department of Spanish, Italian, and Portuguese
  - Claude Moore Health Sciences Library
  - Scholars' Lab
  - University of Virginia Library
  - Language Commons
  - Research & Learning Services
identifier_types:
  local: Local Identifier
  oclc: OCLC
  lccn: LCCN
  issue number: Issue Number
  matrix number: Matrix Number
  music publisher: Music Publisher/Label
  videorecording identifier: Videorecording Identifier
  other: Other
note_types:
  general: General Note
  awards: Awards
  biographical/historical: Bibliographical/Historical Note
  creation/production credits: Creation/Production Credits
  language: Language Note
  local: Local Note
  performers: Performers
  statement of responsibility: Statement of Responsibility
  venue: Venue/Event Date
rights_statements:
  http://rightsstatements.org/vocab/InC/1.0/: In Copyright
  http://rightsstatements.org/vocab/InC-OW-EU/1.0/: In Copyright - EU Orphan Work
  http://rightsstatements.org/vocab/InC-EDU/1.0/: In Copyright - Educational Use Permitted
  http://rightsstatements.org/vocab/InC-NC/1.0/: In Copyright - Non-Commercial Use Permitted
  http://rightsstatements.org/vocab/InC-RUU/1.0/: In Copyright - Rights-Holders Unlocatable or Unidentifiable
  http://rightsstatements.org/vocab/NoC-CR/1.0/: No Copyright - Contractual Restrictions
  http://rightsstatements.org/vocab/NoC-NC/1.0/: No Copyright - Non-Commercial Use Only
  http://rightsstatements.org/vocab/NoC-OKLR/1.0/: No Copyright - Other Known Legal Restrictions
  http://rightsstatements.org/vocab/NoC-US/1.0/: No Copyright - United States
  http://rightsstatements.org/vocab/CNE/1.0/: Copyright Not Evaluated
  http://rightsstatements.org/vocab/UND/1.0/: Copyright Undetermined
  http://rightsstatements.org/vocab/NKC/1.0/: No Known Copyright
name_types:
  cre: Creator
  act: Actor
  arr: Arranger
  aut: Author
  cmp: Composer
  cnd: Conductor
  cng: Cinematographer
  ctb: Contributor
  drt: Director
  dst: Distributor
  edt: Editor
  hst: Host
  itr: Instrumentalist
  ive: Interviewee
  mod: Moderator
  msd: Musical director
  mus: Musician
  nrt: Narrator
  pan: Panelist
  prf: Performer
  pre: Presenter
  pro: Producer
  prn: Production Company
  rcd: Recordist
  aus: Screenwriter
  sng: Singer
  spk: Speaker